In [48]:
import torch
from torch import nn
import numpy as np

In [35]:
def sigmoid(z):
  return 1 / (1 + torch.exp(-z))

In [36]:
x = torch.tensor([
    [0.333, 0.5, 5.0],
    [0.666, 0.25, 10.0],
    [0.999, 0.1, 1.0],
    [0.1, 0.1, 0.2]
])

In [37]:
w1 = torch.tensor([
    [-1.5, -0.5],
    [0.0, 1.0],
    [1.5, 3.0]
])

w2 = torch.tensor([
    [2.5, 0.5, -1.5],
    [3.5, 1.5, 1.5]
])

b1 = torch.tensor([0., 0.], requires_grad=True)
b2 = torch.tensor([0., 0., 0.])

In [38]:
y = torch.tensor([1, 2, 0, 1])
y_hat = sigmoid(x @ w1 + b1) @ w2 + b2

In [39]:
y_hat

tensor([[5.9977e+00, 1.9995e+00, 1.3655e-03],
        [6.0000e+00, 2.0000e+00, 1.1921e-06],
        [4.5091e+00, 1.6465e+00, 6.4578e-01],
        [3.6431e+00, 1.2542e+00, 1.7937e-01]], grad_fn=<AddBackward0>)

In [41]:
loss = torch.nn.CrossEntropyLoss(reduction='mean')
output = loss(y_hat, y)

In [44]:
output.backward()

In [47]:
b1.grad

tensor([0.0962, 0.0980])

In [52]:
import numpy as np
import torch
from torch import nn


class MLPClassifier(nn.Module):
    def __init__(self, input_size, output_size=1):
        super(MLPClassifier, self).__init__()

        self.flatten = nn.Flatten()

        self.input_layer = nn.Linear(input_size, 16)
        self.input_activation = nn.ReLU()

        self.hidden_layer = nn.Linear(16, 16)
        self.hidden_activation = nn.ReLU()

        self.output = nn.Linear(16, output_size)
        self.output_activation = nn.ReLU()

    def forward(self, x):

        x = self.flatten(x)

        x = self.input_layer(x)
        x = self.input_activation(x)

        x = self.hidden_layer(x)
        x = self.hidden_activation(x)

        x = self.output(x)
        x = self.output_activation(x)

        return x

In [55]:
model = MLPClassifier(input_size=128, output_size=10)
input_data = torch.tensor(np.random.rand(1, 128)).float()
model(input_data)

tensor([[0.1344, 0.0450, 0.1175, 0.0000, 0.1303, 0.0000, 0.1518, 0.2282, 0.0000,
         0.0636]], grad_fn=<ReluBackward0>)